--PROGRAM OFFIND SIMPLE INT

SET SERVEROUTPUT ON;

DECLARE
	P NUMBER:=&P;
	R NUMBER:=&R;
	Y NUMBER:=&Y;
	SI NUMBER; 
BEGIN
	SI:=(P*R*Y)/100;
	DBMS_OUTPUT.PUT_LINE('PRINCIPLE AMOUNT:'||P);
	DBMS_OUTPUT.PUT_LINE('RATE OF INT:'||R);
    	DBMS_OUTPUT.PUT_LINE('NO OF YEAR:'||Y);
	DBMS_OUTPUT.PUT_LINE('SIMPLE INT:'||SI);
	
END;
/